### ISSUE TITLE
fcollapse fails with string by variables (Stata 14/MP)

### ISSUE THREAD

**Issue by mcaceresb** [sergiocorreia/ftools#12]
```stata
. sysuse auto, clear
(1978 Automobile Data)

. version 14

. fcollapse price, by(make)
      st_varvaluelabel():   181  Stata returned error
    Factor::store_keys():     -  function returned error
            f_collapse():     -  function returned error
                 <istmt>:     -  function returned error
r(181);
```

**Comment by sergiocorreia** [comment]
Interesting. On Stata 14 this works fine, so I'm guessing that one of the Mata functions changed (and that is not supported by version control AFAIK).

I also checked the code and there is nothing obviously code [with this line](https://github.com/sergiocorreia/ftools/blob/master/src/ftools_main.mata#L188). The only time `st_varvaluelabel()` is called is if `st_isnumvar()` is true, as per the line above.

**Comment by mcaceresb** [comment]
Actually, I get another error with ftools on the server I'm running this on:

```
. sysuse auto
(1978 Automobile Data)

. fisid make
function is_id() not declared in class Factor
(2 lines skipped)
(error occurred while loading fisid.ado)
r(3000);

. fisid price
function is_id() not declared in class Factor
(2 lines skipped)
(error occurred while loading fisid.ado)
r(3000);
```

All works fine on my local machine.

**Comment by sergiocorreia** [comment]
Could you try running `ftools, compile` and then `clear all`?

**Comment by mcaceresb** [comment]
Same errors.

**Comment by sergiocorreia** [comment]
BTW, I tried on Stata/MP 15.0 (Windows) and cannot replicate it either. I don't have access to a Linux version of Stata 15, so I'll probably hold o fixing the bug until I can spot it.

**Comment by mcaceresb** [comment]
I'm closing this. I tried it on a different server with Stata 15 (MP) and the issue is gone, so i reckon it specific to the machine I was using (still odd, however).
