### ISSUE TITLE
fmerge error

### ISSUE THREAD

**Issue by eltreet** [sergiocorreia/ftools#14]
Hi using stata 13.1 mp and facing the following error when running fmerge

Using stata 13.1mp

      is_integers_only():  3253  pk[325815,1] found where real required

                  join():     -  function returned error

                 <istmt>:     -  function returned error

**Comment by sergiocorreia** [comment]
I just realized I never saw your post.

I'm pretty sure this problem was fixed in a recent [update](https://github.com/sergiocorreia/ftools/commit/07dac761b413fec30322d6e562d8d8e97f70e09f), but if that's not the case, please reopen the issue.

Best,
S
