### ISSUE TITLE
data type following fcollapse 

### ISSUE THREAD

**Issue by ajshephard** [sergiocorreia/ftools#15]
```
. which ftools
/home/asheph/ado/plus/f/ftools.ado
*! version 2.24.0 11jan2018
```

Stata's own `collapse` command will promote the storage type of variables. So, if I have 

```
set obs 1000
gen byte x = 1
collapse (sum) x
```

then the sum `x` will be promoted to `double` with a value of `1000` returned.

With `fcollapse` the storage type of the returned variable `x` is not promoted from `byte`, in which case a missing value is returned.

**Comment by sergiocorreia** [comment]
A recent optimization was being too aggressive and causing the issue. It should be working now.
