### ISSUE TITLE
fcollapse incorrectly parses negative weights

### ISSUE THREAD

**Issue by mcaceresb** [sergiocorreia/ftools#17]
```stata
clear
set obs 1
gen x = 1
gen y = -1
preserve
    fcollapse (p30) p30 = x (p50) p50 = x (p70) p70 = x [fw = y]
restore, preserve
    fcollapse (p30) p30 = x (p50) p50 = x (p70) p70 = x [pw = y]
restore, preserve
    fcollapse (p30) p30 = x (p50) p50 = x (p70) p70 = x [aw = y]
restore
```

With collapse, all those instances throw errors. Further,

```stata
set seed 42
clear
set obs 10
gen x = _n
gen y = int(10 * rnormal())
l
preserve
    fcollapse (p10) p10 = x (p50) p50 = x (p90) p90 = x [iw = y]
    l
restore, preserve
    collapse (p10) p10 = x (p50) p50 = x (p90) p90 = x [iw = y]
    l
restore
```

Produces
```stata

     +-----------------+
     | p10   p50   p90 |
     |-----------------|
  1. |  10     1     1 |
     +-----------------+
```

vs
```
     +-----------------+
     | p10   p50   p90 |
     |-----------------|
  1. |   1     5    10 |
```

I think you are running into the same issue I did, and are forgetting to normalize the weights. For percentiles, `collapse` multiplies the weights by number non-missing / sum weights before computing them. This gives the right answer:

```stata
 qui sum y, meanonly
 gen ynorm = y / `r(sum)'
 fcollapse (p10) p10 = x (p50) p50 = x (p90) p90 = x [iw = ynorm]
 l
```

**Comment by sergiocorreia** [comment]
For the first example, I can't seem to replicate it:

```stata
which ftools

clear
set obs 1
gen x = 1
gen y = -1
fcollapse (p30) p30 = x (p50) p50 = x (p70) p70 = x [fw = y]
```

Using yesterday's update (2.24.1 15jan2018), fcollapse returns an error 402 with `negative weights encountered`.

The second example also gives the same results, so perhaps it's all related to the previous lack of `marksample`?

**Comment by mcaceresb** [comment]
Can you try with a different seed? Seed 42 gives the the problem in Stata 13 but not in 15. Consider

```
clear
input float(x y)
 1  -5
 2  -7
 3   3
 4  -5
 5  12
 6   8
 7 -10
 8 -16
 9   2
10  -1
end

preserve
    fcollapse (p10) p10 = x (p50) p50 = x (p90) p90 = x [iw = y]
    l
restore, preserve
    collapse (p10) p10 = x (p50) p50 = x (p90) p90 = x [iw = y]
    l
restore
```

In that case, both versions give a wrong answer.

**Comment by sergiocorreia** [comment]
I ran it on v13 and got what you mentioned. The question for me is what to do. We could

1. Replicate Stata's `collapse` (what do they do exactly, use *negative* weights?)
2. Raise an error
3. Blindly exclude negative weights (like we do with zero weights)

I found an oldish (1998) post from W.Gould discussing iweights: https://www.stata.com/statalist/archive/2003-02/msg00525.html

> [iweights] will apply a formula         blindly -- which formula is supposed to be documented in the Methods         and Formulas section for each command -- and which formula may have no        statistical validity whatsover no matter how the data were gathered.        Why would anyone want this?  Because we have chosen the formula for        blind evaluation so that the result is a userful ingredient for        subsequent calculations that produce meaninful results for meaningful        kinds of weights.  Iweights are for programmers, not analysists.

> Since iweights are for programmers, when we put them into Stata, we included
no extra code to "protect" the programmer from mistakes.  For instance,
iweights can be negative ...

Thus, I kinda get the feeling it might be ok-ish if we just raise an error when encountering negative iweights, unless there is a valid case for those (of which I'm not aware of).

**Comment by mcaceresb** [comment]
Excluding negative weights is a bad idea.

In the context of percentiles, a weight of w_i > 0 roughly means "i adds w_i observations" observations. A weight of -w_i would mean "i deletes w_i observations."

So it would tell the algorithm to ignore the next w_i values. Dropping negative weights would circumvent this, which I think is not sensible.

Throwing an error seems very reasonable to me, on the other hand (while I've already implemented tolerance for negative weights in develop, I'm not 100% that it is useful or worth the hassle).

**Comment by sergiocorreia** [comment]
> Throwing an error seems very reasonable to me, on the other hand (while I've already implemented tolerance for negative weights in develop, I'm not 100% that it is useful or worth the hassle).

I would go with that route too; it's simpler and doing otherwise might [confuse/surprise](https://www.wikiwand.com/en/Principle_of_least_astonishment) people.

**Comment by mcaceresb** [comment]
Maybe I'll go with an error in master... I mean, the more I think about it, most people would be using aweights, fweights, or pweights anyway, right? And none of those allow negative weights. I'll at least add a soft warning, but given it's in place in develop and matching collapse, I'm tempted to leave it in.
