### ISSUE TITLE
join: problems with spaces in filepath

### ISSUE THREAD

**Issue by jfasonntag** [sergiocorreia/ftools#20]
Hi!
Join will throw an error if the filepath for your tempfiles contains spaces. This can be fixed by enclosing "form", "into" and "filename" on lines 24 and 65 of join.ado in additional quotes.

Thanks so much for ceating this great set of tools - it already saved me hours of time!

**Comment by sergiocorreia** [comment]
Fixed, thanks for the detailed bug report!

Best,
Sergio
