### ISSUE TITLE
error with join

### ISSUE THREAD

**Issue by sebastien-willis** [sergiocorreia/ftools#23]
The command -join- appears to fail with the error message 3598 when the master dataset is a tempfile.  See reproducible example below.  I am running Stata 14.0 on mac OS X 10.13.6.

sysuse auto , clear
generate id = _n
preserve
keep id make price mpg
tempfile tmp
save "`tmp'"
restore
keep id foreign
join , into("`tmp'") by(id)

**Comment by sergiocorreia** [comment]
Should be fixed; code was not dealing correctly with the quotes around `tmp`.

Let me know if it works on your side.

Best,
S

**Comment by sebastien-willis** [comment]
I will need to wait for the version of ftools to be updated on the server I'm using, but locally it seems to work fine now, thanks very much.

**Comment by sergiocorreia** [comment]
Great!
