### ISSUE TITLE
fmerge overwrites master dataset's xtset

### ISSUE THREAD

**Issue by James-Traina** [sergiocorreia/ftools#25]
Minor note, unlike Stata's default behavior, fmerge will overwrite the xtset of the master dataset with the xtset of the using dataset.

**Comment by sergiocorreia** [comment]
That's unexpected..

Code below reproduces the bug.. will try to see where is it:

```stata
cls
clear

set obs 2
gen i = _n
gen x = 0
xtset i
tempfile using
save "`using'"

clear
set obs 2
gen i = _n
gen j = _n
xtset j

xtset
fmerge 1:1 i using "`using'", keep(match)
xtset
```

**Comment by sergiocorreia** [comment]
Bug should be fixed. What happens is that Stata internally stores the xtset information as characters (see `char list`). Because I don't just copy notes but also characters, this info was also copied.
