### ISSUE TITLE
join does not clear sortedby macro 

### ISSUE THREAD

**Issue by mcaceresb** [sergiocorreia/ftools#32]
With the following code

```
set seed 42
clear
set obs 20
gen x = _n
gen r = runiform()
drop if r > 0.5
sort r
drop r
tempfile x
save "`x'"

clear
set obs 20
gen y = _n
drop if runiform() > 0.5
sort y
join, by(y=x) from("`x'")
desc
disp "`:sortedby'"
l
```

shows the data is sorted by `y`. However, this is only the case for master/matched observations, which appear first and sorted. Unmatched using observations appear last and unsorted. Ideally sortedby would get cleared after join is run if the results will not be sorted.

- `which join` gives `*! version 2.36.1 13feb2019`
- `which ftools` gives `*! version 2.42.0 28dec2020`

**Comment by sergiocorreia** [comment]
Agree with you. However, are you aware of a straighforward way to unset the sortedby flag?

I searched a bit ([eg](https://www.stata.com/statalist/archive/2014-03/msg00194.html)) but can't find anything besides the obvious slow way (to force a sort). I tried to add and remove variables (set obs followed by drop), and also tried Mata's st_updata().

**Comment by sergiocorreia** [comment]
The only thing that comes to my mind is something like this:

```stata

datasignature
loc sig `r(datasignature)'

loc value = y[1]
replace y = . in 1
replace y = `value' in 1
disp "`:sortedby'"

datasignature
assert "`r(datasignature)'" == "`sig'"
```

Basically, we replace y and then set it back. It's not perfect though, because we can't replace it with itself so we are assuming that the first value of y is not missing, and also need to deal with cases where sortedby has multiple variables, with cases where the first sortedby variable is a string and not a number, etc.

**Comment by mcaceresb** [comment]
@sergiocorreia I think you were the one who turned me onto the trick of fiddling with the sort variable? [Here](https://github.com/sergiocorreia/ftools/blob/master/src/fsort.ado#L17-L31) is the implementation for `fsort` that I used as base for a very similar trick in `hashsort`, [here](https://github.com/mcaceresb/stata-gtools/blob/master/src/ado/_gtools_internal.ado#L1405-L1417). The difference is my version didn't fiddle with an existing value; instead it created then deleted a dummy row of data, but unsure if it introduces other issues I haven't thought about. The data signature check is a good idea to add around the trick.

**Comment by sergiocorreia** [comment]
😮  I had completely forgotten about this, let me see

**Comment by sergiocorreia** [comment]
Just added a fix to the dev branch ( https://github.com/sergiocorreia/ftools/tree/groupreg ).

BTW, plan is to merge the dev branch to master in maybe a few weeks or so.

**Comment by mcaceresb** [comment]
@sergiocorreia v cool, thanks!
