### ISSUE TITLE
Support many to many join

### ISSUE THREAD

**Issue by NilsJPWerner** [sergiocorreia/ftools#34]
Would it be possible to add many to many functionality in the join command that could mimic the joinby command?

**Comment by sergiocorreia** [comment]
Although that's definitely an interesting addition, it's low on my to-do list; too many pending tasks (policy+coauthors) so no idea when I would be able to implement it.

One possibility would be to just partition the data and then run joinby (should be much faster), and another is to code joinby in Mata by combining ftool internals with Mata's kronecker operator.
