### ISSUE TITLE
fegen group behaviour with missing grouping values

### ISSUE THREAD

**Issue by ajshephard** [sergiocorreia/ftools#8]
Firstly, thanks for this excellent set of programs.

```
. which ftools
/home/anon/ado/plus/f/ftools.ado
*! version 2.9.2 06apr2017
```

Suppose we have the data set:

```
hhid	pid
1	1
2	1
2	1
2	
3	1
3	2
4	
4	
```

Using `egen group` will return a missing group value if the grouping values have a missing value. Using `fegen group` does not distinguish between missing and non-missing values. So, running,

```
fegen group1 = group(hhid pid)
egen group2 = group(hhid pid)
```

produces the data set:

```
hhid	pid	group1	group2
1	1	1	1
2	1	2	2
2	1	2	2
2		3	
3	1	4	3
3	2	5	4
4		6	
4		6	
```

which may cause problems if the users program expects the same behaviour as the stata command.

Best, Andrew

**Comment by sergiocorreia** [comment]
Andrew,

Thanks for the detailed report. I agree with your assessment. There was a bug in the group command that prevented the correct behavior.

With the latest update (just uploaded to Github, but not yet on SSC), missing values will be maintained as such unless you specify the `missing` option (i.e. what `egen group` does)

Best,
Sergio
